### ISSUE TITLE
Compile error on resultant `missing argument: body`

### ISSUE THREAD

**Issue by Myriad-Dreamin** [OrangeX4/mitex#21] opened 2023-12-21 18:09 UTC
```tex
\displaystyle\operatorname{tr}A=\sum\limits_{i}(A)_{ii}
```

**Comment by OrangeX4** [comment] 2023-12-22 03:41
This is actually a parser bug caused by greedy commands and left1 operators prioritization error.

https://github.com/OrangeX4/mitex/blob/64fe6153d2ca5ff4de7d0881abbee6aee8557004/crates/mitex-parser/tests/ast/command.rs#L53-L128

**Comment by OrangeX4** [comment] 2023-12-22 05:41
Fixed by #25

**Closed by OrangeX4** 2023-12-22 05:41 UTC
Labels: bug, T Parser
